# Useful Information:
# - NPC Skin is only work If the entity type is a PLAYER
# - The offset is a location that is subtracted from the spawn point
islandNPC:
  entityType: VILLAGER
  skinName: "aglerr"
  hologram:
    height: 0.3
    lines:
      - "&bBarry"
      - "&e&lCLICK"
  offset:
    x: 1
    y: 0
    z: -1

moveNPCItem:
  material: VILLAGER_SPAWN_EGG
  name: "&eMove Barry"
  customModelData: 0
  glowing: true
  lore:
    - "&7Place this anywhere on your"
    - "&7island to move Barry."

npcOptions:
  disableGravity: true
  anchor: true
  lookClose: true
  clickCommands:
    - "[CONSOLE] broadcast Barry barry, barry barry (Owner: {player})"
    - "[PLAYER] say I'm talking to Barry."
    - "[MESSAGE] &7You are now talking to barry!"

messages:
  noPermission: "&cYou don't have enough permission!"
  reload: "&aYou have reloaded the configuration!"
  invalidPlayer: "&cThat player is not online!"
  targetNoIsland: "&cTarget doesn't have an island!"
  npcResetted: "&aYou have resetted the target island npc!"
  moveNPCMessage: "&aI have given you an egg, place this where you would like me to move!"
  help:
    - "&e&lIslandNPC &7- by aglerr"
    - "&e/islandnpc help &7- shows all help messages"
    - "&e/islandnpc reload &7- reload the configuration"
    - "&e/islandnpc reset <player> &7- reset island npc on specific player's island"